CREATE TABLE ITG_DOO_HEADER_ALL(
    ID_HEADER VARCHAR(50),
    ORDER_NUMBER VARCHAR(50),
    HEADER_ID_ERP NUMBER(20),
    SOURCE_TRANSACTION_NUMBER VARCHAR(20),
    SOURCE_TRANSACTION_SYSTEM VARCHAR(10),
    BUSINESS_UNIT_NAME VARCHAR(30),
    BUYING_PARTY_NAME VARCHAR(60),
    BUYING_PARTY_CONTACT_NAME VARCHAR(40),
    TRANSACTION_TYPE VARCHAR(30),
    REQUESTED_SHIP_DATE VARCHAR(40),
    REQUESTED_FULFILLMENT_ORGANIZATION_NAME VARCHAR(50),
    TRANSACTIONAL_CURRENCY_NAME VARCHAR(50),
    CUSTOMER_PO_NUMBER VARCHAR2(30),
    PAYMENT_TERMS VARCHAR(50),
    STATUS VARCHAR(40),
    CLIENT_ID VARCHAR(100),
    CREATE_DATE TIMESTAMP,
    CREATE_BY VARCHAR(40),
    LAST_UPDATE_BY VARCHAR(40),
    LAST_UPDATE_DATE TIMESTAMP,
    PRIMARY KEY (ID_HEADER)
);

CREATE TABLE ITG_DOO_LINES(
    ID_LINE VARCHAR(50),
    ID_HEADER VARCHAR2(50),
    HEADER_ID_ERP NUMBER(20),
    LINE_NUMBER VARCHAR(10),
    LINE_ID_ERP NUMBER(20),
    PRODUCT_NUMBER VARCHAR(50),
    UNIT_SELLING_PRICE VARCHAR(10),
    ORDERED_QUANTITY VARCHAR(10),
    ORDERED_UOM_CODE VARCHAR(20),
    TRANSACTIONAL_CATEGORY_CODE VARCHAR(20),
    TRANSACTIONAL_LINE_TYPE VARCHAR(15),
    CREATE_DATE TIMESTAMP,
    CREATE_BY VARCHAR(40),
    LAST_UPDATE_DATE TIMESTAMP,
    LAST_UPDATE_BY VARCHAR(40),
    PRIMARY KEY (ID_LINE)
);

CREATE TABLE ITG_DOO_LOAD_ERROR(
    ID_LOAD VARCHAR(50),
    FILE_NAME VARCHAR(50),
    CONTENT  CLOB
    ID_HEADER VARCHAR(50),
    ID_CLIENT VARCHAR(50)
);


CREATE TABLE ITG_WAVES_PICK(
    ID_WAVE VARCHAR(50),
    BATCH_ID NUMBER(10),
    SHIP_FROM_ORGANIZATION_CODE VARCHAR(30),
    ORDER_TYPE_CODE VARCHAR(20),
    ORDER_ID NUMBER(20),
    ORDER_NUMBER VARCHAR(25),
    SHIP_CONFIRM_RULE VARCHAR(50),
    RETURN_MESSAGE VARCHAR2(400)
);


CREATE TABLE ITG_FROM_ORG_LOAD(
    ID_LOAD_ORG VARCHAR(50),
    ORG_CODE VARCHAR(60),
    ORG_NAME VARCHAR(70),
    SHIP_CRITERIA VARCHAR(50),
    SHIP_RULE VARCHAR(50),
    HEADER_ID VARCHAR(60),
    CLIENT_ID VARCHAR(50)
);

--ON_AWAIT
--RUNNING
--ERROR
--AWAIT_SHIPPING
--AWAIT_BILLING

--SELECT  --wdd.source_header_number,
--        wie.*--                   ,
--        --wddi.*                  ,
--        --wdd.*
--FROM    FUSION.WSH_INTERFACE_ERRORS wie      ,
--        fusion.WSH_DEL_DETAILS_INTERFACE wddi,
--        FUSION.wsh_delivery_details wdd
--WHERE   wie.interface_id            = wddi.DELIVERY_DETAIL_INTERFACE_ID (+)
--        AND wddi.delivery_detail_id = wdd.delivery_detail_id (+)
--        and wdd.source_header_number LIKE '17066%'
