CREATE OR REPLACE TRIGGER TR_CREATE_HEADER
 BEFORE INSERT ON ITG_DOO_HEADER_ALL
 REFERENCING NEW AS NEW FOR EACH ROW
 DECLARE mongo VARCHAR2(50) := '';
 BEGIN
    mongo := random_uuid();
    :NEW.ID_HEADER := mongo; 
    :NEW.CREATE_DATE := CURRENT_TIMESTAMP;
    :NEW.CREATE_BY := 'SYSTEM';
    :NEW.LAST_UPDATE_BY := 'SYSTEM';
    :NEW.LAST_UPDATE_DATE := CURRENT_TIMESTAMP;
END;

CREATE OR REPLACE TRIGGER TR_CREATE_LINES
 BEFORE INSERT ON ITG_DOO_LINES
 REFERENCING NEW AS NEW FOR EACH ROW
 DECLARE mongo VARCHAR2(50) := '';
 BEGIN
    mongo := random_uuid();
    :NEW.ID_LINE := mongo; 
    :NEW.CREATE_DATE := CURRENT_TIMESTAMP;
    :NEW.CREATE_BY := 'SYSTEM';
    :NEW.LAST_UPDATE_BY := 'SYSTEM';
    :NEW.LAST_UPDATE_DATE := CURRENT_TIMESTAMP;
END;

CREATE OR REPLACE TRIGGER TR_CREATE_ORG_LOAD
 BEFORE INSERT ON ITG_FROM_ORG_LOAD
 REFERENCING NEW AS NEW FOR EACH ROW
 DECLARE mongo VARCHAR2(50) := '';
 BEGIN
    mongo := random_uuid();
    :NEW.ID_LOAD_ORG := mongo;
END;
